server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, 
        - id: writing
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**, 
        - id: point
          uri: http://point-service:80
          predicates:
            - Path=/points/**, /getPoints/**
        - id: subscriber
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /subscriptions/**, /getSubscriptions/**
        - id: platform
          uri: http://localhost:8086
          predicates:
            - Path=/books/**, /getBookByIds/**
        - id: aigeneration
          uri: http://localhost:8087
          predicates:
            - Path=/aiBookGenerations/**, /processedResults/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**, 
        - id: writing
          uri: http://writing:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: point
          uri: http://point-service:80 # <-- 'point'를 'point-service'로 변경
          predicates:
            - Path=/points/**, 
        - id: subscriber
          uri: http://subscriber:8080
          predicates:
            - Path=/users/**, /subscriptions/**, 
        - id: platform
          uri: http://platform:8080
          predicates:
            - Path=/books/**, 
        - id: aigeneration
          uri: http://aigeneration:8080
          predicates:
            - Path=/aiBookGenerations/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
