server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**,
        - id: writing
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**,
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/points/**, /getPoints/**
        - id: subscription
          uri: http://localhost:8085
          predicates:
            - Path=/users/**, /subscriptions/**, /getSubscriptions/**
        - id: platform
          uri: http://localhost:8086
          predicates:
            - Path=/books/**, /getBookByIds/**
        - id: aigeneration
          uri: http://localhost:8081
          predicates:
            - Path=/aiBookGenerations/**, /processedResults/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8082
          predicates:
            - Path=/authors/**,
        - id: writing
          uri: http://writing:8083
          predicates:
            - Path=/manuscripts/**,
        - id: point
          uri: http://point:8084
          predicates:
            - Path=/points/**, /getPoints/**
        - id: subscription
          uri: http://subscription:8085
          predicates:
            - Path=/users/**, /subscriptions/**, /getSubscriptions/**
        - id: platform
          uri: http://platform:8086
          predicates:
            - Path=/books/**, /getBookByIds/**
        - id: aigeneration
          uri: http://aigeneration:8081
          predicates:
            - Path=/aiBookGenerations/**, /processedResults/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
